### ISSUE TITLE
Daylight Detector height

### ISSUE THREAD

**Issue by franz-dalitz** [JoakimThorsen/MCPropertyEncyclopedia#12]
Hey, you got daylight detector as 2 px in external height, shouldnt that be 6? might be wrong, but i play in a community where block heights are super important and 2 would be shorter than a trapdoor which they definitely are not

**Comment by JoakimThorsen** [comment]
Thanks! Interestingly 2, 4 & 6 pixels are listed under "all (including internal)" hitboxes, must have been human error.
Unrelated, but I don't recognize your username. Out of curiosity, where did you find out about this page?

**Comment by franz-dalitz** [comment]
Because what i do in minecraft is called "Wargears". Basically redstone nerds get together on a server and build tnt cannons / war machines, group as teams with teamnames and secret technology and fight at serverwide events. We need exact knowledge about most stats a minecraft block has so i googled for a while and eventually got this github project recommended by someone on a technical minecraft discord server. I dont know how much you know about tnt cannons or if you even care but that stuff really gets quite complex to the point where people who have been in the scene for a good 4-7 years still have to research for weeks/months just to build a certain cannon a certain way.

**Comment by JoakimThorsen** [comment]
Ahh, I've heard of that before yeah, cool. Feel free to suggest additions that you all would otherwise find useful btw!
