### ISSUE TITLE
Website not working on Firefox

### ISSUE THREAD

**Issue by kikugie** [JoakimThorsen/MCPropertyEncyclopedia#23]
What it says on the tin:
![image](https://github.com/JoakimThorsen/MCPropertyEncyclopedia/assets/50152507/9226da91-7561-41fb-847e-f3292c27e58b)

Idk really what else to write in the report, I have win10, latest stable build of firefox and these addons:
![image](https://github.com/JoakimThorsen/MCPropertyEncyclopedia/assets/50152507/fd3aab4b-7329-4007-b865-f030684b2465)
uBlock is even disabled for it.

## Plsfixkthx

**Comment by JoakimThorsen** [comment]
hmmm. can you copy/send a screenshot of your console output? should be viewable by clicking F12

**Comment by kikugie** [comment]
![image](https://github.com/JoakimThorsen/MCPropertyEncyclopedia/assets/50152507/4199309f-9f38-4ab5-a7f6-d25c83108e1f)

**Comment by JoakimThorsen** [comment]
I've pushed (an attempt at) a fix just now. Give it a couple of minutes then do Ctrl+Shift+R to reload without chache

**Comment by kikugie** [comment]
That works

**Comment by JoakimThorsen** [comment]
alright, cool
