### ISSUE TITLE
Sorting items by "XP From Smelting" is incorrect

### ISSUE THREAD

**Issue by Mac15001900** [JoakimThorsen/MCPropertyEncyclopedia#31]
When sorting items by "XP From Smelting", the decimal part seems to be treated as its own number, resulting in the order being incorrect, as 0.15 is treated as larger than 0.7.
The values appear in the following order (when sorted descendingly):
2, 1, 0.35, 0.15, 0.7, 0.3, 0.2, 0.1

**Comment by JoakimThorsen** [comment]
Fixed now :)
Issue appeared as a side-effect of trying to fix how it sorted strings with numbers in them, but I readded a clause for comparing pure numbers to other pure numbers
