### ISSUE TITLE
Item Property Thingy filter allows incorrect items

### ISSUE THREAD

**Issue by enbyd** [JoakimThorsen/MCPropertyEncyclopedia#9]
Steps to reproduce:
1. Open Item Property Thingy
2. Deselect "Unstackable" and "64" from the "**Stackablilty**" dropdown, in any order
(alternative 2. Deselect all options in the "**Stackability**" dropdown
3. Deselect "Yes" from the "**Survival Obtainable**" menu

Expected behavior:
The table should display only the items that are 16 stackable and unobtainable in survival items (of which there are none, so an empty table), but seemingly all of the 64 stackable, unobtainable in survival items are still listed.
(With alternative step 2: The table should not display any items, as there are no items without a "Stackability" measure, but seemingly all of the 64 stackable, unobtainable in survival items are still listed, same as before.)

**Comment by JoakimThorsen** [comment]
Thanks, turns out the issue was item max stackability being stored as quoted-number strings. I'll push a fix
